#This file analyses anonymized data provided by "loadAnonymiseSaveData.R" in exp-specific directory
#This script expects the working directory to be "newTraj_repo/analysis"
library(readr)

dataDir<- file.path("..","dataAnonymized")
expName<- "youngOld"

anonDataFile<- paste0(expName,".tsv") #generated by loadAnonymiseSaveData.R in dataPreprocess directory
rawData<- readr::read_tsv( file.path(dataDir,expName,anonDataFile),  show_col_types=FALSE)
  
excludeFixationViolations = TRUE; proportnTrialsMustFixate = .6
excludeDidntReach75pct = TRUE


#check data counterbalancing of this exp
source( file.path("helpers","checkCounterbalancing.R") )
t<- checkCombosOccurEqually(rawData, c("numObjects","numTargets"), tolerance=.01 )
#Visually inspect trials for each combination for each subject
#table(rawData$numObjects,rawData$numTargets,rawData$IDnum)

# checkCombosOccurEqually(rawData, c("numObjects","numTargets","ringToQuery") )
# checkCombosOccurEqually(rawData, c("condition","leftOrRight") )
# checkCombosOccurEqually(rawData, c("condition","leftOrRight","offsetXYring0") ) #NO?
# checkCombosOccurEqually(rawData, c("numObjects","numTargets","speed") )  

#end data importation

datAnalyze <-rawData

factorsForBreakdown<-  c("")
#factorsForBreakdownForAnalysis = c('exp','offsetXYring0','leftOrRight')

#Also need to get age and sex from somewhere.. a manual copy of the Sharepoint participant sheet with only those columns?

#Eyemovement exclusion zone numbers
exclusionDeg = 1 #in any direction from fixation
widthPix = 800
heightPix = 600
monitorWidth = 39.5 #cm
viewdist = 57 #cm
widthScreenDeg =  2*(atan((monitorWidth/2)/viewdist) /pi*180)
pixelsPerDegree = widthPix / widthScreenDeg
exclusionPixels = exclusionDeg * pixelsPerDegree
centralZoneWidthPix = exclusionPixels*2
centralZoneHeightPix = exclusionPixels*2 #assumes the monitor is correct aspect ratio so that pixels are square


sanityCheckEyeTracking=TRUE
if (sanityCheckEyeTracking) {
  library(ggplot2)
  h<-ggplot(filter(dat,exp=="circleOrSquare_twoTargets"),
            aes(x=maxXdev,y=maxYdev,color=file)) + geom_point() +facet_grid(~subject)  #Have a look at fixation positions
  quartz("circleOrSquare_twoTargets"); show(h)
  h<-ggplot(filter(dat,exp=="offCenter"),
            aes(x=maxXdev)) + geom_histogram()+ facet_grid(~subject) #Have a look at fixation positions
  quartz("offCenter"); show(h)
}
dat$correct = dat$orderCorrect /3
dat$chanceRate= 1 / dat$numObjects

#https://github.com/alexholcombe/speed-tf-VSS14/blob/master/analyseExps/doAllAnalyses_E4ab.R
for (iv in c("logTf","speed","logSpd","tf")) {
  cat('Fitting data, extracting threshes, plotting with iv=',iv)
  source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
  fitParms$iv<- iv
  fitParmsAll<-rbind(fitParmsAll,fitParms)
  source('plotIndividDataWithPsychometricCurves.R')
  source("extractThreshes.R") #provides threshes
  thrAll<-rbind(thrAll,threshes)
  #below is old way, saving separate threshes
  #   varName=paste("threshes_",iv,"_",expName,sep='') #combine threshes
  #   assign(varName,threshes)
  #   save(list=varName,file=paste(dataDir,varName,".Rdata",sep='')) #e.g. threshes_tf_123targets269objects.Rdata
  #   cat("Saved",varName)
}
